### ISSUE TITLE
Bug on down/revive script

### ISSUE THREAD

**Issue by UrstMcRedHead** [CaptainPStar/co10_Escape#178] opened 2024-04-03 04:38 UTC
After updating a vanilla dedicated server to 2.16 a bug causing keyboard controls to stop  working after getting revived by other players. Also on going unconscious in these cases there would be multiple messages, and multiple ragdol models generated. 
On aborting, and getting back on the server the issue would temporarily fix itself. until the player goes down again.

Stream link:
https://www.twitch.tv/videos/2108435501

System info:
The server is a Debian 64bit system running steamcmd with Wine.
The players are running a mix of Windows, and Linux systems.

**Comment by aussie-battler** [comment] 2024-04-06 10:57
II think this is the answer, it seems to work. 

[https://github.com/CaptainPStar/Revive/blob/908c5bcda6bc5c2e6873a23d259fb0817bd7c687/functions/Revive/fn_HandleDamage.sqf](url)

`params ["_unit","_bodyPart","_amountOfDamage","_killer","_projectile","_context"];

if (_context > 2) exitWith {};

//["HitFace","HitNeck","HitPelvis","HitAbdomen","HitDiaphragm","HitChest","HitArms","HitHead","HitBody","HitHands","HitLegs"]
//["face_hub","neck","pelvis","spine1","spine2","spine3","arms","head","body","hands","legs"]
if (alive _unit
	&& {_amountOfDamage >= 1}
	&& {!(_unit getVariable ["AT_Revive_isUnconscious",false])}
	&& {_bodyPart in ["","head","face_hub","head_hit","neck","spine1","spine2","spine3","pelvis","body"]}
) then {
	_unit setDamage 0;
	_unit allowDamage false;
	_amountOfDamage = 0;
	[_unit, _killer] spawn ATR_FNC_Unconscious;
};
_amountOfDamage;`

Ill push a pull request on github if it doesnt have any bugs.

**Comment by CaptainPStar** [comment] 2024-04-06 17:43
No need, I already prepped a fix that will be published tomorrow.

**Comment by aussie-battler** [comment] 2024-04-07 00:31
@UrstMcRedHead my fix doesnt work. When you get killed by explosions it bypasses the unconscious state & you become a default soldier.

**Comment by benji91919** [comment] 2024-04-09 20:41
I downloaded the new escape version but i still get the revive bug.

**Comment by navelbarnet** [comment] 2024-04-10 20:05
Hello! 
First of all, **thank you** for this mission and the time you put into making it! Me and my friends play it regularly and it is the best mission we ever played!
Just wanted to post that we also tried the newest version of the mission Commit [9158b2c](https://github.com/CaptainPStar/co10_Escape/commit/9158b2c) and still got the issue. Before we get the bugg, it seems like our characters spawn 2 or more ragdolls when we get unconsious. That is a givaway that the bug will happen if we revive that player. Just wanted to give that info IF it would help in any way.
Looking forward to a fix! Keep up the good work and thanks again!

**Comment by CaptainPStar** [comment] 2024-04-11 19:13
Thanks @navelbarnet . Indeed the bug is not fixed yet. But I have a concept I need to implement that will fix it quite sure.
The double-ragdoll is not a bug. It is caused by a different timing in animation I tried to fix the problem.

**Comment by CaptainPStar** [comment] 2024-04-13 13:06
Fixed in #f0cc369c2c5ec6c050afec615bbdf582ad00dbbc

**Closed by CaptainPStar** 2024-04-13 13:06 UTC
